#!/bin/sh
# vim: ft=sh

export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway

dbus-update-activation-environment --systemd  --all
exec dbus-run-session sway --unsupported-gpu "$@"
