#!/bin/sh

set -e
exec 2> /dev/null

uuid="`cat /proc/sys/kernel/random/uuid`"
dir="`git rev-parse --git-dir`"

trap 'rm -f "$dir/$uuid.tags"' EXIT
git ls-files | ctags --kinds-all=* --fields=* --tag-relative=yes -L - -I - -f"$dir/$uuid.tags" --languages=c,c++
mv "$dir/$uuid.tags" "$dir/tags"
