#!/bin/sh

set -e

uuid="`cat /proc/sys/kernel/random/uuid`"
dir="`git rev-parse --git-dir`"

trap 'rm -f "$dir/$uuid.tags"' EXIT
git ls-files | ctags --tag-relative -L - -f"$dir/$uuid.tags" --languages=-javascript,sql,java,html
mv "$dir/$uuid.tags" "$dir/tags"
