#!/bin/sh

set -e

uuid="`cat /proc/sys/kernel/random/uuid`"
dir="`git rev-parse --git-dir`"

trap 'rm -f "$dir/$uuid.tags"' EXIT
git ls-files | ctags --c++-kinds=+lpx --c-kinds=+lpx --fields=+iatS --extras=+q --tag-relative=yes -L - -I - -f"$dir/$uuid.tags" --languages=c,c++
mv "$dir/$uuid.tags" "$dir/tags"
