#!/bin/sh

set -e

dir=/tmp/i3status
mkdir -p $dir

temp=$(find /sys/devices/platform/coretemp.0 -name 'temp*_input' | sort | head -1)
if [ ! -z "$temp" ]; then
  ln -sf "$temp" "$dir/cpu_temp"
fi

battery=$(find /sys/class/power_supply/ -name 'BAT*' | sort | head -1)
if [ ! -z "$battery" ]; then
  ln -sf "$battery/uevent" "$dir/battery"
fi

exec i3status
