# ~/.bash_profile

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

if [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
  [[ -f $XDG_CONFIG_HOME/displayrc ]] && . $XDG_CONFIG_HOME/displayrc
fi
